[package]
name = "linux-remote"
version = "0.1.0"
edition = "2021"

[dependencies]
input-linux = "0.5.0"
mpris = "2.0.0"
nix = "0.26.2"
notify-rust = "4.9.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.27.0", features = ["full"] }
